baseURL = "https://okyzyr.github.io/lifedebugger/"
title = "Debugging Mode On"
theme = "PaperMod"
languageCode = "pl"

[params]
description = "Blog o moim wolnym czasie, zainteresowaniach i projektach."