baseURL = "https://okyzyr.github.io/FuzzyLogic/"
title = "Fuzzy Logic"
theme = "PaperMod"
languageCode = "pl"
publishDir = "docs"

[params]
  description = "Blog o moich zainteresowaniach i projektach."
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  ShowCodeCopyButtons = true
  ShowTags = true

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tagi"
    url = "/tags/"
    weight = 10
  
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 0
